# -----------------------------------------------------------------------------
# Compatibility layer for KernelFunctions.jl and Functors.jl
# -----------------------------------------------------------------------------

using Functors

# -----------------------------------------------------------------------------
# Functors.jl integration for automatic differentiation
# -----------------------------------------------------------------------------

"""
Make kernels compatible with Functors.jl for parameter optimization.
This allows packages like Flux.jl and Optimisers.jl to traverse and update
kernel parameters automatically.
"""
Functors.@functor GeneralizedCauchyKernel
Functors.@functor KummerKernel
Functors.@functor BetaKernel
Functors.@functor TricomiKernel

# -----------------------------------------------------------------------------
# Utility functions for RFF-based kernel approximation
# -----------------------------------------------------------------------------

"""
    rff_kernelmatrix(basis::RandomFourierFeatures.RFFBasis, X::AbstractVector)

Compute approximate kernel matrix using Random Fourier Features.

Given a collection of data points `X` and an RFF basis `basis`, computes
the approximate kernel matrix K̂ where K̂[i,j] ≈ k(X[i], X[j]).

# Arguments
- `basis`: RFF basis generated by `sample_generalized_rff_basis`
- `X`: Vector of data points (each point is a vector)

# Returns
- `K`: Approximate kernel matrix (N × N) where N = length(X)

# Example
```julia
using GeneralizedRFF, KernelFunctions

# Create kernel and sample RFF basis
k = GeneralizedCauchyKernel(1.5, 2.0)
basis = sample_generalized_rff_basis(k, 3, 200)

# Generate data
X = [rand(3) for _ in 1:50]

# Compute approximate kernel matrix
K_approx = rff_kernelmatrix(basis, X)

# Compare with exact kernel matrix
K_exact = kernelmatrix(k, X)
```
"""
function rff_kernelmatrix(basis::RandomFourierFeatures.RFFBasis, X::AbstractVector)
    N = length(X)
    Φ = zeros(2 * basis.M, N)

    for (i, x) in enumerate(X)
        Φ[:, i] = basis(x)
    end

    return Φ' * Φ
end

"""
    rff_kernelmatrix(rng::AbstractRNG, kernel::Kernel, X::AbstractVector, M::Int)

Convenience function to sample RFF basis and compute kernel matrix in one call.

# Arguments
- `rng`: Random number generator
- `kernel`: Kernel function
- `X`: Vector of data points
- `M`: Number of random features

# Returns
- `K`: Approximate kernel matrix (N × N)

# Example
```julia
using GeneralizedRFF, Random

rng = MersenneTwister(1234)
k = GeneralizedCauchyKernel(1.5, 2.0)
X = [rand(rng, 3) for _ in 1:50]
K = rff_kernelmatrix(rng, k, X, 200)
```
"""
function rff_kernelmatrix(
    rng::Random.AbstractRNG,
    kernel::KernelFunctions.Kernel,
    X::AbstractVector,
    M::Int
)
    input_dim = length(first(X))
    basis = sample_generalized_rff_basis(rng, kernel, input_dim, M)
    return rff_kernelmatrix(basis, X)
end
