# -----------------------------------------------------------------------------
# Compatibility layer for KernelFunctions.jl and Functors.jl
# -----------------------------------------------------------------------------

using Functors

# -----------------------------------------------------------------------------
# Functors.jl integration for automatic differentiation
# -----------------------------------------------------------------------------

# Make kernels compatible with Functors.jl for parameter optimization.
# This allows packages like Flux.jl and Optimisers.jl to traverse and update
# kernel parameters automatically.
# We specify which fields are trainable (excluding metric which is fixed).
Functors.@functor GeneralizedCauchyKernel (α, β)
Functors.@functor KummerKernel (α, β, γ)
Functors.@functor BetaKernel (α, β, γ)
Functors.@functor TricomiKernel (α, β, γ)

# -----------------------------------------------------------------------------
# Utility functions for RFF-based kernel approximation
# -----------------------------------------------------------------------------

"""
    rff_kernelmatrix(basis::RFFBasis, X::AbstractVector)

Compute approximate kernel matrix using Random Fourier Features.

Given a collection of data points `X` and an RFF basis `basis`, computes
the approximate kernel matrix K̂ where K̂[i,j] ≈ k(X[i], X[j]).

# Arguments
- `basis`: RFF basis generated by `sample_generalized_rff_basis`
- `X`: Vector of data points (each point is a vector)

# Returns
- `K`: Approximate kernel matrix (N × N) where N = length(X)

# Example
```julia
using GeneralizedRandomFourierFeatures, KernelFunctions

# Create kernel and sample RFF basis
k = GeneralizedCauchyKernel(1.5, 2.0)
basis = sample_generalized_rff_basis(k, 3, 200)

# Generate data
X = [rand(3) for _ in 1:50]

# Compute approximate kernel matrix
K_approx = rff_kernelmatrix(basis, X)

# Compare with exact kernel matrix
K_exact = kernelmatrix(k, X)
```
"""
function rff_kernelmatrix(basis::RFFBasis, X::AbstractVector)
    # Stack all points into a matrix and wrap with ColVecs
    X_mat = hcat(X...)
    X_colvecs = KernelFunctions.ColVecs(X_mat)

    # Get all features at once
    features = basis(X_colvecs)

    # Stack features into a matrix
    N = length(X)
    M = length(features[1])  # Feature dimension
    Φ = zeros(M, N)
    for i in 1:N
        Φ[:, i] = features[i]
    end

    return Φ' * Φ
end

"""
    rff_kernelmatrix(rng::AbstractRNG, kernel::Kernel, X::AbstractVector, M::Int)

Convenience function to sample RFF basis and compute kernel matrix in one call.

# Arguments
- `rng`: Random number generator
- `kernel`: Kernel function
- `X`: Vector of data points
- `M`: Number of random features

# Returns
- `K`: Approximate kernel matrix (N × N)

# Example
```julia
using GeneralizedRandomFourierFeatures, Random

rng = MersenneTwister(1234)
k = GeneralizedCauchyKernel(1.5, 2.0)
X = [rand(rng, 3) for _ in 1:50]
K = rff_kernelmatrix(rng, k, X, 200)
```
"""
function rff_kernelmatrix(
    rng::Random.AbstractRNG,
    kernel::KernelFunctions.Kernel,
    X::AbstractVector,
    M::Int
)
    input_dim = length(first(X))
    basis = sample_generalized_rff_basis(rng, kernel, input_dim, M)
    return rff_kernelmatrix(basis, X)
end
